### ISSUE TITLE
Error executing `brew install`

### ISSUE THREAD

**Issue by leodemoura** [leanprover/homebrew-lean#1]
I get the following error when I try to execute `brew install`

```
Error: No head is defined for lean
```

BTW, the command `brew tap leanprover/lean` seems to work fine.

**Comment by leodemoura** [comment]
It seems the problem was option `--HEAD` used in the README.md page.
If I omit it, then lean installs.
However, I have another problem. When I try to run `lean` I get the error

```
dylib: Library nod loaded: /usr/local/lib/libtcmalloc.4.dylib
Reason: Incompatible library version: lean requires version 7.0.0 or later, but libtcmalloc.4.dylib provides version 6.0.0
```

**Comment by leodemoura** [comment]
I tried to delele `libtcmalloc`, and install Lean again using

```
brew rm lean
brew install lean
```

But, I get the error message regarding lua. I had to use

```
brew unlink lua52
brew link lua
```

to fix the error message.
Then, lean was installed successfully, but I'm still getting the tcmalloc error

**Comment by leodemoura** [comment]
I tried

```
brew rm gperftools
brew install gperftools
```

but, I'm still getting the tcmalloc error.

**Comment by soonhokong** [comment]
Dear Leo,

I'll fix this today.

Soonho Kong
soonhok@cs.cmu.edu

On Thu, Jan 15, 2015 at 2:07 AM, Leonardo de Moura <notifications@github.com

**Comment by leodemoura** [comment]
Thanks!

**Comment by soonhokong** [comment]
Dear Leo,
1. I updated README.md file to remove "--HEAD" option. Now, we provide users with two precompiled binaries of Lean (one for Maverics - 10.9 and one for Yosemite - 10.10). The installation should be done in 5 - 10 secs.
2. The binary 'lean' has the following dependencies

```
$ otool -L /usr/local/bin/lean
/usr/local/bin/lean:
    /usr/local/lib/libmpfr.4.dylib (compatibility version 6.0.0, current version 6.2.0)
    /usr/local/lib/libgmp.10.dylib (compatibility version 13.0.0, current version 13.0.0)
    /usr/local/lib/libtcmalloc.4.dylib (compatibility version 7.0.0, current version 7.4.0)
    /usr/local/lib/liblua.5.2.dylib (compatibility version 5.2.0, current version 5.2.3)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

In short, it depends on mpfr, gmp, tcmalloc, and lua. The last two (libc++ and libSystem.B) are the ones that come with OS X, which we shouldn't worry about.

In [lean.rb](https://github.com/leanprover/homebrew-lean/blob/master/lean.rb) file, we have the following lines to specify the dependencies:

```
 15   depends_on 'gmp'
 16   depends_on 'mpfr'
 17   depends_on 'lua'
 18   depends_on 'google-perftools'
```

When I tested, homebrew installed those dependencies before installing lean, and it worked well without a problem.

However, you experienced problems with the tcmalloc. I think one solution is to disable using tcmalloc when we build the bottle (pre-compiled binaries) by using `-DTCMALLOC=OFF`. If you think it's OK to do, I'll make the change.

**Comment by leodemoura** [comment]
I think using`-DTCMALLOC=OFF` is a good solution.
In the future, we can use our own allocator to avoid this dependency.

**Comment by soonhokong** [comment]
I removed the tcmalloc depdendency in d236198b0e6c3ed0e4ae6e7c248588077f44832a. When the next commit is pushed to leanprover/lean repo, the build will be triggered. I'll double check the result and close this issue.

**Comment by leodemoura** [comment]
Thanks!

**Comment by soonhokong** [comment]
```
$ otool -L /usr/local/bin/lean
/usr/local/bin/lean:
    /usr/local/lib/libmpfr.4.dylib (compatibility version 6.0.0, current version 6.2.0)
    /usr/local/lib/libgmp.10.dylib (compatibility version 13.0.0, current version 13.0.0)
    /usr/local/lib/liblua.5.2.dylib (compatibility version 5.2.0, current version 5.2.3)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```
