### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by spl** [leanprover/homebrew-lean#15]
Spurred by https://github.com/leanprover/lean/issues/1971, I think this repository needs some TLC, since it hasn't seen an update in over a year. I'm willing to help if someone explains how the scripts should be run. I looked at them, but I just want to get it from you in case I miss anything. Also, I will need the Bintray account information if I should upload bottles, or I suppose I could create a new Bintray account if necessary.

**Comment by soonho-tri** [comment]
Per email discussion with @spl, I think it's best to delete this repository as there is already the `lean` formula in the homebrwe core. I'll do this this Saturday (8 Sep). If anyone has a different idea, please let us know here.
