### ISSUE TITLE
no emacs installation when lean is installed via homebrew

### ISSUE THREAD

**Issue by soonhokong** [leanprover/homebrew-lean#5]
While assisting @awodey, I had this problem.

After installing lean via homebrew, there was no `/usr/local/share/emacs/site-lisp/lean` directory which should be there. On my macs, homebrew does put `.el` files under `/usr/local/share/emacs/site-lisp/lean`. I will double check.

**Comment by soonhokong** [comment]
For @awodey, I manually copied the files at `/usr/local/share/emacs/site-lisp/lean`.

**Comment by leodemoura** [comment]
Same here. I just reinstalled brew, and installed Lean.
I had the same problem: `/usr/local/share/emacs/site-lisp/lean` is missing

**Comment by soonhokong** [comment]
@leodemoura, could you check the latest version by running:

```
brew update
brew install lean
```

and do

```
ls -l /usr/local/share/emacs/site-lisp
```

If you find a symbolic link "lean -> ../../../Cellar/lean/0.2.0-<version>/share/emacs/site-lisp/lean", it means things are working.

**Comment by leodemoura** [comment]
I will try

**Comment by leodemoura** [comment]
It worked, but the leanemacs script does not work because it uses the emacs terminal version.

I think `brew` is a really bad option for the end user.
First, it is not a binary distribution. It actually compiles Lean source code.
The user needs to install xcode, install brew, ...
I also had many problems with `brew`. For example, as far as I can tell `brew update` doesn't work.
I executed `brew update && brew upgrade` and Lean was not upgraded. I tried `brew update && brew install lean` and it said it was already installed. I had to use `brew uninstall lean`, and then `brew install lean`. It takes a long time to compile Lean. Moreover, in the process, I got a ton of cryptic error messages from brew. 

For developers, brew is also a bad solution. It is much better to use `git`.

**Comment by soonhokong** [comment]
> It worked, but the leanemacs script does not work because it uses the emacs terminal version.

Yes, `/usr/bin/emacs` is emacs22. There are at least three ways people install emacs24 on Mac.
- via package mgmt: homebrew, macport, fink (I'm using homebrew)
- http://emacsformacosx.com/
- http://aquamacs.org (for example, Steve Awodey is using it)

It's not clear to me what we need to do when a user of `leanemacs` does not have an emacs-24 installation on his/her machine. One solution is to ask them to visit http://emacsformacosx.com/ or http://aquamacs.org and install emacs-24 and re-run `leanemacs` again. Another solution is to install one of them inside of `leanemacs` and proceed.

> First, it is not a binary distribution. It actually compiles Lean source code.

The current solution (homebrew-lean) is supposed to provide binary distributions. 'supposed to' means that it was broken (see #3). I just fix the shasum manually and disable automatic-update for now. In short, **it should work now**. `brew install lean` should use the binary distribution and finish in seconds.

The problem is tricky because we need to provide a binary distribution per OS X major version (mainly 10.10, 10.9). I wrote a script to build lean and to upload a binary distribution to `gh-pages` branch of `leanprover/homebrew-lean`. Then we need to update `lean.rb` (homebrew formula) to point the binary distributions with the right SHA values. The last part is somewhat buggy so it fails to use the binary distributions from time to time.. I'll fix it and re-enable the automatic update.

> The user needs to install xcode, install brew, ...

I agree this is not an ideal solution.

I just checked how Coq does the business of a package distribution for OS X. They provide 1) OS X package (`.dmg`), 2) support brew, macport, and flink. I think we need to do the same thing, esp the `.dmg`. [cpack](http://www.cmake.org/Wiki/CMake:CPackPackageGenerators#PackageMaker_.28OSX_only.29) provides a way to do this.

> I also had many problems with brew. For example, as far as I can tell brew update doesn't work.

I see. I think it's because of the current version number scheme which homebrew version of lean is using. For example, it's `0.2.0-git10357f3f53471630faab6cec1d712b9fd470c313` for the latest version. homebrew is internally using git and I thought as long as the formula of new version is a HEAD of the old one, homebrew always detects it as a newer version. Maybe it's not the case and we need to make sure that the relation `old_version_name` < `new_version_name` holds lexicographically. Actually, that is the case for the ubuntu-ppa case, and there we're using something like `0.2.0.20150130151615.git099111db323cc6aa647d8849ae369024ebf8053c` which includes a commit date/time.

> For developers, brew is also a bad solution. It is much better to use git.

I understand that brew has some problems. But, how do we replace it with git? You mean we maintain a binary repository for OS X and ask people to clone and `git pull` to upgrade?

**Comment by leodemoura** [comment]
> In short, it should work now. brew install lean should use the binary distribution and finish in seconds.

I will try to install it tonight. 
I'm planning to buy a Mac mini and leave it in my office.
So, it will be easier for me to make this kind of test.

> I just checked how Coq does the business of a package distribution for OS X. They provide 1) OS X package (.dmg), 2) support brew, macport, and flink. I think we need to do the same thing, esp the .dmg. cpack provides a way to do this.

For sure, a `.dmg` will be much more user friendly.
Even tar-ball + installation script (like PVS) is more user friendly.

> I understand that brew has some problems. But, how do we replace it with git?

What I meant is: for developers, it is easier to clone the Lean repository and build the binary following the instructions we provided [here](https://github.com/leanprover/lean/blob/master/doc/make/osx-10.9.md).  I'm serious, I'm not making a joke. `brew` barely works for me. I spent many hours (several times) trying to install Lean using `brew`. It failed most times. The error messages are incomprehensible. Moreover, a failure seems to leave "leftovers" that prevent you from installing later versions.

**Comment by soonhokong** [comment]
> For sure, a .dmg will be much more user friendly.

I did some google search:
- [Julia](http://julialang.org/downloads/) provides a `.dmg` file and [here](https://github.com/JuliaLang/julia/blob/4f7b787bcadf2ce4bb516179b36e0c7f29739b3d/contrib/mac/app/Makefile#L17-L34) is the part of their `Makefile` which generates it.
- [K-3D]() uses cmake to generate a `.dmg`. [Here](https://github.com/K-3D/k3d/tree/master/distribution/osx/bundle) is a related directory.

> What I meant is: for developers, it is easier to clone the Lean repository and build the binary following the instructions we provided here. I'm serious, I'm not making a joke. brew barely works for me. I spent many hours (several times) trying to install Lean using brew. It failed most times. The error messages are incomprehensible. Moreover, a failure seems to leave "leftovers" that prevent you from installing later versions

I can feel the pain that you had.. I hope this time `brew install lean` works smoothly. In case you think you have some leftover in your system, please try to remove them by running `brew cleanup` and `rm /Library/Caches/Homebrew/lean*`. It should help.

**Comment by soonhokong** [comment]
The original problem of this issue, "no emacs installation when lean is installed via homebrew", was handled. After fixing #3, we can install lean via `brew install leanprover/lean/lean`. I also checked that `brew upgrade` is also working.

It seems that the remaining task is to create a `.dmg`. Let me open a new issue for that and close this one.
