### ISSUE TITLE
Building lean with OSX El Capitan

### ISSUE THREAD

**Issue by rodrigogribeiro** [leanprover/homebrew-lean#9]
The following message was returned when I tried to update lean using home-brew on OSX El Capitán today:

Last 15 lines from /Users/rodrigo/Library/Logs/Homebrew/lean/03.make:
1107/1108 Test #1107: c_env_test ........................................   Passed    1.71 sec
        Start 1108: thread_test
1108/1108 Test #1108: thread_test .......................................   Passed    1.04 sec

99% tests passed, 1 tests failed out of 1108

Label Time Summary:
expensive    =   7.18 sec

Total Test time (real) = 192.00 sec

The following tests FAILED:
    1088 - max_sharing (SEGFAULT)
Errors while running CTest
make: **\* [test] Error 8

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/leanprover/homebrew-lean/issues

Warning:

**Comment by soonhokong** [comment]
On my OSX 10.11 (El Capitan) machine, I don't get a segmentation fault from `max_sharing` test. But it gives me `invalid_read` warnings when I run valgrind with it. I'm not sure that it's an OSX 10.11 specific issue or a compiler issue (clang). I'll check it on OSX 10.10 machine later.

FYI, on a Ubuntu machine, valgrind gives no warning for `max_sharing` test.

**Comment by leodemoura** [comment]
(I think) the issue has been fixed.

**Comment by rodrigogribeiro** [comment]
It worked. Thanks.

**Comment by soonhokong** [comment]
Thank you @leodemoura !
